@startuml
!include inc/module_t.pu
!include inc/hci_transport_interface.pu

interface hci_t <<callback structure>>{
    set_data_cb( callback ) /*callback(Location&, BT_HDR*)*/
    transmit_command(BT_HDR* command, command_complete_cb, command_status_cb, void * context )
    transmit_command_futured(BT_HDR*)
    transmit_downward(uint16_t type, void* data )
}

class package_segment{
}

class hci_layer <<static>> {
    {static} package_segment
}

hci_layer -|> module_t
hci_layer -|> hci_t
hci_layer -|> hci_transport_evt
hci_layer -> hci_transport_api
hci_layer -> package_segment

class hci_transport_implementation{
}
hci_transport_implementation -|> hci_transport_api
hci_transport_implementation -> hci_transport_evt

@enduml
